# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildPush_React_image
  displayName: Build & Push Docker Images
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build&Push_React_Image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'harshit1019/gofood-frontend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

    - task: Docker@2
      displayName: Build&Push_Nodejs_Image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'harshit1019/gofood-backend'
        command: 'buildAndPush'
        Dockerfile: '/backend/'
        tags: '$(tag)'

    