# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Docker Image Push
  displayName: Build & Push Docker Images
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build_&_Push_Nodejs_Image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'harshit1019/gofood-backend'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
        tags: '$(tag)'

- stage: Deploy_Backend
  displayName: Deploy_backend_to_WebApp
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'goFood-service'
        appName: 'backendMern'
        containers: 'harshit1019/gofood-backend:$(tag)'